### ISSUE TITLE
v1.4.0

### ISSUE THREAD

**Issue by taichunmin** [alexislours/acnh-translations#4]
How can I update translation to v1.4.0? I need the newer version of `TWzh/STR_MailDesign.csv`. Can you teach me?

**Comment by alexislours** [comment]
Hi, you can find an updated version of this repository here: https://github.com/alexislours/acnh-message/blob/master/String_TWzh/STR_MailDesign.csv
The game strings contain both hexadecimal and UTF-8 so I had to create a new repository to generate them automatically.

**Comment by taichunmin** [comment]
Thank you!
